---
- name: Creates and deletes s3 bucket
  hosts: localhost 
  tasks:
    - name: S3 management
      aws_s3:
        bucket: "{{bucket}}"     # Give a name
        mode: "{{mode}}"         # get #put #delete #create  #geturl  #getstr  #delobj  #list
        region: "{{region}}"