--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  become: yes
  become_method: sudo

  tasks:
    - name: Create instances
      ec2:
        key_name: user_ANSIBLE_TOWER
        group: Ansible Tower
        instance_type: t2.micro
        image: ami-0b3655835197107a9
        count: 3
        vpc_subnet_id: subnet-699fd047
        region: us-east-2