---
- name: Install r1soft server
  hosts: 35.237.56.40 
  become: yes
  become_method: sudo
  tasks:
    # This line for CentOS 7
    - block:        
      - name: Create Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo

      - name: Install r1soft server
        package:
          name: serverbackup-enterprise
          state: latest
        notify: R1SOFT_INSTALLED_ON_CENTOS_7

  handlers:
    - name: R1SOFT_INSTALLED_ON_CENTOS_7
      systemd:
         name: sbm-agent
         state: restarted
