---
- name: Create an s3 bucket
  hosts: localhost 
  tasks:
    - name: Create an s3 bucket
      aws_s3:
        bucket: "{{bucketname}}"
        mode: "{{mode}}"         # get #put #delete #create  #geturl  #getstr  #delobj  #list