---
- name: Restarts all types of OS
  # vars_prompt:
  #   - name: OS_TYPE
  #     prompt: "What OS to restart?"
  #     private: no
  hosts: web
  tasks:
    - name: Restarts
      become: yes
      become_method: sudo
      # when: ansible_distribution == "{{OS_TYPE}}"
      reboot: