- name: Creates Internet Gateway (igw)
  hosts: localhost
  tasks:
    - name: Creating igw
      ec2_vpc_igw:
        vpc_id: "{{vpc_id}}"                    # Add VPC ID
        state: present
        region: "{{region}}"
        resource_tags: "{{resource_tags}}"
      register: igw